# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "uni-core-auth"
main = "src/index.ts"
compatibility_date = "2025-01-29"

[observability]
enabled = true

# Smart Placement
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# [placement]
# mode = "smart"

# Bindings
# Bindings allow your Worker to interact with resources on the Cloudflare Developer Platform, including
# databases, object storage, AI inference, real-time communication, and more.
# https://developers.cloudflare.com/workers/runtime-apis/bindings/

[[d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "a2325432-487c-4eae-b561-3309eefa692f"
preview_database_id = "a2325432-487c-4eae-b561-3309eefa692f"

[[kv_namespaces]]
binding = "KV"
id = "137cf26972d44eb9b45bb7881cc08be6"
preview_id = "137cf26972d44eb9b45bb7881cc08be6"

# Environment Variables
# https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
# [vars]
# MY_VARIABLE = "production_value"

# Note: Use secrets to store sensitive data.
# https://developers.cloudflare.com/workers/configuration/secrets/

# Static Assets
# https://developers.cloudflare.com/workers/static-assets/binding/
# [assets]
# directory = "./public/"
# binding = "ASSETS"

# Service Bindings (communicate between multiple Workers)
# https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"
