# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "uni-core-news"
compatibility_date = "2025-01-29"

[observability]
enabled = true

# Smart Placement
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# [placement]
# mode = "smart"

# Bindings
# Bindings allow your Worker to interact with resources on the Cloudflare Developer Platform, including
# databases, object storage, AI inference, real-time communication, and more.
# https://developers.cloudflare.com/workers/runtime-apis/bindings/

[[d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "a2325432-487c-4eae-b561-3309eefa692f"
preview_database_id = "a2325432-487c-4eae-b561-3309eefa692f"

# Environment Variables
# https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
[vars]
ALLOWED_ORIGIN = "http://localhost:3000"
COOKIE_DOMAIN = "localhost"

